---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/locations/barcrawl":
    get:
      summary: crawl location
      responses:
        '200':
          description: successful
  "/locations":
    get:
      summary: list locations
      responses:
        '200':
          description: successful
    post:
      summary: create location
      responses:
        '200':
          description: successful
  "/locations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show location
      responses:
        '200':
          description: successful
    patch:
      summary: update location
      responses:
        '200':
          description: successful
    put:
      summary: update location
      responses:
        '200':
          description: successful
    delete:
      summary: delete location
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
